require("ledson.remap")
require("ledson.set")
require("ledson.rosepine")
--vim.cmd("colorscheme solarized-osaka")
--vim.cmd("colorscheme tokyonight-night")
vim.cmd("colorscheme vague")
--vim.cmd("colorscheme rose-pine")
--require("ledson.indent")
